# Generated by Django 4.2.9 on 2024-01-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dept_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('designation', models.CharField(choices=[('ASSOCIATE', 'Associate'), ('TEAM LEADER', 'TL'), ('MANAGER', 'Manager')], default='ASSOCIATE', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept_management.dept')),
                ('reporting_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_management.emp')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
