# Generated by Django 4.2.9 on 2024-01-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emp_management.emp'),
        ),
    ]
